# Site settings
title: Million Dollar Curve
email: curves@cryptoexperts.com
description: An elliptic curve everyone can trust.
baseurl: "/million-dollar-curve/" # the subpath of your site, e.g. /blog/
url: "http://cryptoexperts.github.io" # the base hostname & protocol for your site
twitter_username: CryptoExperts
github_username:  CryptoExperts
url_source_code: "https://github.com/CryptoExperts/million-dollar-curve"
url_paper_relative: "specifications/2016-01-02_trap-me-if-you-can.pdf"

# Build settings
markdown: kramdown
